version: '6.1'
servers:
  - id: default
    listeners:
      - port: 25
        address: 127.0.0.1
environment:
  controlsocket:
    chmod: '0660'
    group: staff
  privdrop:
    group: halon
    user: halon
  rlimit:
    nofile: 70000
  umask: '0027'
  uuid:
    version: 4
scripting:
  rootpath: /workspaces/dmarc